In [19]:
# ==================================================
# Student Productivity Analytics Project
# Feature Engineering Notebook
# ==================================================

# Goal:
# Create advanced behavioral and productivity features
# for analytics and machine learning.

In [2]:
# ==================================================
# Import Libraries
# ==================================================

import pandas as pd
import numpy as np
import os

In [3]:
# ==================================================
# Connect Google Drive
# ==================================================

from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
# ==================================================
# Project Paths
# ==================================================

PROJECT_PATH = "/content/drive/MyDrive/student-productivity-analytics"

CLEANED_DATA_PATH = f"{PROJECT_PATH}/data/cleaned"

PROCESSED_DATA_PATH = f"{PROJECT_PATH}/data/processed"

os.makedirs(PROCESSED_DATA_PATH, exist_ok=True)

print("Paths Ready!")

Paths Ready!

In [5]:
# ==================================================
# Load Cleaned Dataset
# ==================================================

dataset_path = (
    f"{CLEANED_DATA_PATH}/"
    "student_productivity_cleaned.csv"
)

df = pd.read_csv(dataset_path)

print("Dataset Loaded Successfully!")

Dataset Loaded Successfully!

In [6]:
# ==================================================
# Preview Dataset
# ==================================================

df.head()

,Student_ID,Date,Persona,Age,Gender,Department,Year_of_Study,Sleep_Hours,Study_Hours,Screen_Time_Hours,Stress_Level,Focus_Score,Mood_Score,Attendance_Percentage,Assignment_Completion,Productivity_Score,Exam_Score,Burnout_Risk,Study_Efficiency,Wellness_Score
0,1,2025-01-01,High Performer,18,Female,Information Technology,2,7.9,5.4,4.6,5.5,7.8,7.8,100.0,99.8,51.6,65.0,Low,10.156250,3.85
1,1,2025-01-02,High Performer,18,Female,Information Technology,2,7.9,5.0,3.5,4.2,6.1,6.3,96.2,89.2,43.5,49.9,Low,8.316667,3.79
2,1,2025-01-03,High Performer,18,Female,Information Technology,2,6.8,4.1,5.5,3.8,8.1,6.6,100.0,89.6,50.1,52.2,Low,10.235294,3.56
3,1,2025-01-04,High Performer,18,Female,Information Technology,2,7.8,4.9,3.7,3.4,9.9,8.0,100.0,100.0,63.3,64.0,Low,10.847458,4.50
4,1,2025-01-05,High Performer,18,Female,Information Technology,2,7.7,3.5,2.7,4.2,8.7,8.2,100.0,90.3,53.5,54.8,Low,12.177778,4.28

In [7]:
# ==================================================
# Productivity Efficiency Score
# ==================================================

df["Productivity_Efficiency"] = (
    df["Productivity_Score"] /
    (df["Study_Hours"] + 1)
)

df["Productivity_Efficiency"] = (
    df["Productivity_Efficiency"]
    .round(2)
)

print("Productivity Efficiency Created!")

Productivity Efficiency Created!

In [8]:
# ==================================================
# Digital Distraction Score
# ==================================================

df["Digital_Distraction_Score"] = (
    df["Screen_Time_Hours"] * 0.6
    -
    df["Study_Hours"] * 0.3
    +
    (10 - df["Focus_Score"]) * 0.4
)

df["Digital_Distraction_Score"] = (
    df["Digital_Distraction_Score"]
    .round(2)
)

print("Distraction Score Created!")

Distraction Score Created!

In [9]:
# ==================================================
# Wellness Index
# ==================================================

df["Wellness_Index"] = (
    df["Sleep_Hours"] * 0.4
    +
    df["Mood_Score"] * 0.3
    -
    df["Stress_Level"] * 0.3
)

df["Wellness_Index"] = (
    df["Wellness_Index"]
    .round(2)
)

print("Wellness Index Created!")

Wellness Index Created!

In [10]:
# ==================================================
# Study Consistency Score
# ==================================================

study_std = (
    df.groupby("Student_ID")["Study_Hours"]
    .transform("std")
)

df["Study_Consistency_Score"] = (
    10 - study_std
)

df["Study_Consistency_Score"] = (
    df["Study_Consistency_Score"]
    .clip(0, 10)
    .round(2)
)

print("Consistency Score Created!")

Consistency Score Created!

In [11]:
# ==================================================
# Sleep Deficit Score
# ==================================================

df["Sleep_Deficit"] = (
    8 - df["Sleep_Hours"]
)

df["Sleep_Deficit"] = (
    df["Sleep_Deficit"]
    .clip(lower=0)
    .round(2)
)

print("Sleep Deficit Created!")

Sleep Deficit Created!

In [12]:
# ==================================================
# Burnout Risk Score
# ==================================================

df["Burnout_Risk_Score"] = (
    df["Stress_Level"] * 0.4
    +
    df["Sleep_Deficit"] * 0.3
    +
    df["Screen_Time_Hours"] * 0.2
    +
    (10 - df["Mood_Score"]) * 0.1
)

df["Burnout_Risk_Score"] = (
    df["Burnout_Risk_Score"]
    .round(2)
)

print("Burnout Risk Score Created!")

Burnout Risk Score Created!

In [13]:
# ==================================================
# Performance Category
# ==================================================

conditions = [
    df["Exam_Score"] >= 80,
    df["Exam_Score"] >= 60,
    df["Exam_Score"] >= 40
]

categories = [
    "Excellent",
    "Good",
    "Average"
]

df["Performance_Category"] = np.select(
    conditions,
    categories,
    default="Poor"
)

print("Performance Categories Created!")

Performance Categories Created!

In [14]:
# ==================================================
# High Risk Flag
# ==================================================

df["High_Risk_Flag"] = np.where(
    (
        (df["Burnout_Risk_Score"] > 7)
        &
        (df["Exam_Score"] < 50)
    ),
    1,
    0
)

print("High Risk Flag Added!")

High Risk Flag Added!

In [15]:
# ==================================================
# New Feature Preview
# ==================================================

df[[
    "Productivity_Efficiency",
    "Digital_Distraction_Score",
    "Wellness_Index",
    "Study_Consistency_Score",
    "Burnout_Risk_Score",
    "Performance_Category"
]].head()

,Productivity_Efficiency,Digital_Distraction_Score,Wellness_Index,Study_Consistency_Score,Burnout_Risk_Score,Performance_Category
0,8.06,2.02,3.85,8.91,3.37,Good
1,7.25,2.16,3.79,8.91,2.78,Average
2,9.82,2.83,3.56,8.91,3.32,Average
3,10.73,0.79,4.50,8.91,2.36,Good
4,11.89,1.09,4.28,8.91,2.49,Average

In [16]:
# ==================================================
# Final Dataset Info
# ==================================================

df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 28 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Student_ID                 15000 non-null  int64
 1   Date                       15000 non-null  object
 2   Persona                    15000 non-null  object
 3   Age                        15000 non-null  int64
 4   Gender                     15000 non-null  object
 5   Department                 15000 non-null  object
 6   Year_of_Study              15000 non-null  int64
 7   Sleep_Hours                15000 non-null  float64
 8   Study_Hours                15000 non-null  float64
 9   Screen_Time_Hours          15000 non-null  float64
 10  Stress_Level               15000 non-null  float64
 11  Focus_Score                15000 non-null  float64
 12  Mood_Score                 15000 non-null  float64
 13  Attendance_Percentage      15000 non-null  float64
 14  Assignment_Completion      15000 non-null  float64
 15  Productivity_Score         15000 non-null  float64
 16  Exam_Score                 15000 non-null  float64
 17  Burnout_Risk               15000 non-null  object
 18  Study_Efficiency           15000 non-null  float64
 19  Wellness_Score             15000 non-null  float64
 20  Productivity_Efficiency    15000 non-null  float64
 21  Digital_Distraction_Score  15000 non-null  float64
 22  Wellness_Index             15000 non-null  float64
 23  Study_Consistency_Score    15000 non-null  float64
 24  Sleep_Deficit              15000 non-null  float64
 25  Burnout_Risk_Score         15000 non-null  float64
 26  Performance_Category       15000 non-null  object
 27  High_Risk_Flag             15000 non-null  int64
dtypes: float64(18), int64(4), object(6)
memory usage: 3.2+ MB

Student_ID                   0
Date                         0
Persona                      0
Age                          0
Gender                       0
Department                   0
Year_of_Study                0
Sleep_Hours                  0
Study_Hours                  0
Screen_Time_Hours            0
Stress_Level                 0
Focus_Score                  0
Mood_Score                   0
Attendance_Percentage        0
Assignment_Completion        0
Productivity_Score           0
Exam_Score                   0
Burnout_Risk                 0
Study_Efficiency             0
Wellness_Score               0
Productivity_Efficiency      0
Digital_Distraction_Score    0
Wellness_Index               0
Study_Consistency_Score      0
Sleep_Deficit                0
Burnout_Risk_Score           0
Performance_Category         0
High_Risk_Flag               0
dtype: int64

In [17]:
# ==================================================
# Save Processed Dataset
# ==================================================

processed_path = (
    f"{PROCESSED_DATA_PATH}/"
    "student_productivity_processed.csv"
)

df.to_csv(processed_path, index=False)

print("Processed Dataset Saved!")

Processed Dataset Saved!

In [18]:
# ==================================================
# Verify Processed Files
# ==================================================

os.listdir(PROCESSED_DATA_PATH)

['student_productivity_processed.csv']